spring.application.name=wacdo

spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.url=${MYSQL_URL}://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect


jwt.secret=3kF9mP2nQ5rS8tU1vW4xY7zA0bC6dE9fG2hJ5kL8mN1oP4qR7sT0uV3wX6yZ9aB2cD5eF8gH1iJ4kM7nO0pQ3rS6tU9vW2xY5zA8bC1dE4fG7hJ0kL3mN6oP9qR2sT5uV8wX1yZ4aB7cD0eE3fG6hH9iJ2kM5nO8pQ1rS4tU7vW0xY3zA6bC9dE2fG5hJ8kL1mN4oP7qR0sT3uV6wX9yZ2aB5cD8eF1gH4iJ7kM0nO3pQ6rS9tU2vW5xY8zA1bC4dE7fG0hJ3kL6mN9oP2qR5sT8uV1wX4yZ7aB0cD3eF6gH9iJ2kM5nO8pQ1rS4
jwt.expiration = 86400000

## Logs détaillés pour débugger
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG